### ISSUE TITLE
is the datatset available?

### ISSUE THREAD

**Issue by zhouzhouha** [LilydotEE/Dynamic3D#2]
Could you please share the link for the dataset if possible? Thank you

**Comment by LilydotEE** [comment]
Thanks for your interest. Because the other work about is under review. We will share the link of the dataset, once the work is accepted.

**Comment by LilydotEE** [comment]
> Could you please share the link for the dataset if possible? Thank you

Thanks for your interest. Because the other work about it is under review. We will share the link of the dataset, once the work is accepted.
